In [1]:
import requests
from bs4 import BeautifulSoup

### COLLECTING DATA OF ICC MEN'S T20 WORLD CUP 2022

In [2]:
response = requests.get('https://stats.espncricinfo.com/ci/engine/records/team/match_results.html?id=2022%2F23;trophy=89;type=season')
soup = BeautifulSoup(response.content, 'html.parser')

In [3]:
import pandas as pd
df = pd.read_html(str(soup.table))
df[0]

,Team 1,Team 2,Winner,Margin,Ground,Match Date,Scorecard
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830
5,Sri Lanka,U.A.E.,Sri Lanka,79 runs,Geelong,"Oct 18, 2022",T20I # 1832
6,Ireland,Scotland,Ireland,6 wickets,Hobart,"Oct 19, 2022",T20I # 1833
7,West Indies,Zimbabwe,West Indies,31 runs,Hobart,"Oct 19, 2022",T20I # 1834
8,Netherlands,Sri Lanka,Sri Lanka,16 runs,Geelong,"Oct 20, 2022",T20I # 1835
9,Namibia,U.A.E.,U.A.E.,7 runs,Geelong,"Oct 20, 2022",T20I # 1836
10,Ireland,West Indies,Ireland,9 wickets,Hobart,"Oct 21, 2022",T20I # 1837
11,Scotland,Zimbabwe,Zimbabwe,5 wickets,Hobart,"Oct 21, 2022",T20I # 1838
12,Australia,New Zealand,New Zealand,89 runs,Sydney,"Oct 22, 2022",T20I # 1839
13,Afghanistan,England,England,5 wickets,Perth,"Oct 22, 2022",T20I # 1840
14,Ireland,Sri Lanka,Sri Lanka,9 wickets,Hobart,"Oct 23, 2022",T20I # 1841
15,India,Pakistan,India,4 wickets,Melbourne,"Oct 23, 2022",T20I # 1842
16,Bangladesh,Netherlands,Bangladesh,9 runs,Hobart,"Oct 24, 2022",T20I # 1843
17,South Africa,Zimbabwe,no result,NaN,Hobart,"Oct 24, 2022",T20I # 1844
18,Australia,Sri Lanka,Australia,7 wickets,Perth,"Oct 25, 2022",T20I # 1845
19,England,Ireland,Ireland,5 runs,Melbourne,"Oct 26, 2022",T20I # 1846
20,Afghanistan,New Zealand,abandoned,NaN,Melbourne,"Oct 26, 2022",T20I # 1846a
21,Bangladesh,South Africa,South Africa,104 runs,Sydney,"Oct 27, 2022",T20I # 1847
22,India,Netherlands,India,56 runs,Sydney,"Oct 27, 2022",T20I # 1848
23,Pakistan,Zimbabwe,Zimbabwe,1 run,Perth,"Oct 27, 2022",T20I # 1849
24,Afghanistan,Ireland,abandoned,NaN,Melbourne,"Oct 28, 2022",T20I # 1849a
25,Australia,England,abandoned,NaN,Melbourne,"Oct 28, 2022",T20I # 1849b
26,New Zealand,Sri Lanka,New Zealand,65 runs,Sydney,"Oct 29, 2022",T20I # 1850
27,Bangladesh,Zimbabwe,Bangladesh,3 runs,Brisbane,"Oct 30, 2022",T20I # 1851
28,Netherlands,Pakistan,Pakistan,6 wickets,Perth,"Oct 30, 2022",T20I # 1852
29,India,South Africa,South Africa,5 wickets,Perth,"Oct 30, 2022",T20I # 1853
30,Australia,Ireland,Australia,42 runs,Brisbane,"Oct 31, 2022",T20I # 1855
31,Afghanistan,Sri Lanka,Sri Lanka,6 wickets,Brisbane,"Nov 1, 2022",T20I # 1856
32,England,New Zealand,England,20 runs,Brisbane,"Nov 1, 2022",T20I # 1858
33,Netherlands,Zimbabwe,Netherlands,5 wickets,Adelaide,"Nov 2, 2022",T20I # 1859
34,Bangladesh,India,India,5 runs,Adelaide,"Nov 2, 2022",T20I # 1860
35,Pakistan,South Africa,Pakistan,33 runs,Sydney,"Nov 3, 2022",T20I # 1861
36,Ireland,New Zealand,New Zealand,35 runs,Adelaide,"Nov 4, 2022",T20I # 1862
37,Australia,Afghanistan,Australia,4 runs,Adelaide,"Nov 4, 2022",T20I # 1864
38,England,Sri Lanka,England,4 wickets,Sydney,"Nov 5, 2022",T20I # 1867
39,Netherlands,South Africa,Netherlands,13 runs,Adelaide,"Nov 6, 2022",T20I # 1871
40,Bangladesh,Pakistan,Pakistan,5 wickets,Adelaide,"Nov 6, 2022",T20I # 1872
41,India,Zimbabwe,India,71 runs,Melbourne,"Nov 6, 2022",T20I # 1873
42,New Zealand,Pakistan,Pakistan,7 wickets,Sydney,"Nov 9, 2022",T20I # 1877
43,England,India,England,10 wickets,Adelaide,"Nov 10, 2022",T20I # 1878
44,England,Pakistan,England,5 wickets,Melbourne,"Nov 13, 2022",T20I # 1879

In [ ]:
df[0].to_csv('match_results.csv')

### COLLECTING BATTING AND BOWLING DATA

In [4]:
import re
dict1 = {}
links = soup.find_all('a', attrs={"class" : "data-link", "href":re.compile("^/ci/engine/match")})
for link in links:
    string = link.string
    base_url = 'https://stats.espncricinfo.com'
    pg_content = requests.get(base_url+link.get('href'))
    dict1[string] = pg_content
    print(pg_content)
    print(link.get('href'))

<Response [200]>
/ci/engine/match/1298135.html
<Response [200]>
/ci/engine/match/1298136.html
<Response [200]>
/ci/engine/match/1298137.html
<Response [200]>
/ci/engine/match/1298138.html
<Response [200]>
/ci/engine/match/1298139.html
<Response [200]>
/ci/engine/match/1298140.html
<Response [200]>
/ci/engine/match/1298141.html
<Response [200]>
/ci/engine/match/1298142.html
<Response [200]>
/ci/engine/match/1298143.html
<Response [200]>
/ci/engine/match/1298144.html
<Response [200]>
/ci/engine/match/1298145.html
<Response [200]>
/ci/engine/match/1298146.html
<Response [200]>
/ci/engine/match/1298147.html
<Response [200]>
/ci/engine/match/1298148.html
<Response [200]>
/ci/engine/match/1298149.html
<Response [200]>
/ci/engine/match/1298150.html
<Response [200]>
/ci/engine/match/1298151.html
<Response [200]>
/ci/engine/match/1298152.html
<Response [200]>
/ci/engine/match/1298153.html
<Response [200]>
/ci/engine/match/1298154.html
<Response [200]>
/ci/engine/match/1298155.html
<Response [200]>
/ci/engine/match/1298156.html
<Response [200]>
/ci/engine/match/1298157.html
<Response [200]>
/ci/engine/match/1298158.html
<Response [200]>
/ci/engine/match/1298159.html
<Response [200]>
/ci/engine/match/1298160.html
<Response [200]>
/ci/engine/match/1298161.html
<Response [200]>
/ci/engine/match/1298162.html
<Response [200]>
/ci/engine/match/1298163.html
<Response [200]>
/ci/engine/match/1298164.html
<Response [200]>
/ci/engine/match/1298165.html
<Response [200]>
/ci/engine/match/1298166.html
<Response [200]>
/ci/engine/match/1298167.html
<Response [200]>
/ci/engine/match/1298168.html
<Response [200]>
/ci/engine/match/1298169.html
<Response [200]>
/ci/engine/match/1298170.html
<Response [200]>
/ci/engine/match/1298171.html
<Response [200]>
/ci/engine/match/1298172.html
<Response [200]>
/ci/engine/match/1298173.html
<Response [200]>
/ci/engine/match/1298174.html
<Response [200]>
/ci/engine/match/1298175.html
<Response [200]>
/ci/engine/match/1298176.html
<Response [200]>
/ci/engine/match/1298177.html
<Response [200]>
/ci/engine/match/1298178.html
<Response [200]>
/ci/engine/match/1298179.html

In [5]:
dict1

{'T20I # 1823': <Response [200]>,
 'T20I # 1825': <Response [200]>,
 'T20I # 1826': <Response [200]>,
 'T20I # 1828': <Response [200]>,
 'T20I # 1830': <Response [200]>,
 'T20I # 1832': <Response [200]>,
 'T20I # 1833': <Response [200]>,
 'T20I # 1834': <Response [200]>,
 'T20I # 1835': <Response [200]>,
 'T20I # 1836': <Response [200]>,
 'T20I # 1837': <Response [200]>,
 'T20I # 1838': <Response [200]>,
 'T20I # 1839': <Response [200]>,
 'T20I # 1840': <Response [200]>,
 'T20I # 1841': <Response [200]>,
 'T20I # 1842': <Response [200]>,
 'T20I # 1843': <Response [200]>,
 'T20I # 1844': <Response [200]>,
 'T20I # 1845': <Response [200]>,
 'T20I # 1846': <Response [200]>,
 'T20I # 1846a': <Response [200]>,
 'T20I # 1847': <Response [200]>,
 'T20I # 1848': <Response [200]>,
 'T20I # 1849': <Response [200]>,
 'T20I # 1849a': <Response [200]>,
 'T20I # 1849b': <Response [200]>,
 'T20I # 1850': <Response [200]>,
 'T20I # 1851': <Response [200]>,
 'T20I # 1852': <Response [200]>,
 'T20I # 1853': <Response [200]>,
 'T20I # 1855': <Response [200]>,
 'T20I # 1856': <Response [200]>,
 'T20I # 1858': <Response [200]>,
 'T20I # 1859': <Response [200]>,
 'T20I # 1860': <Response [200]>,
 'T20I # 1861': <Response [200]>,
 'T20I # 1862': <Response [200]>,
 'T20I # 1864': <Response [200]>,
 'T20I # 1867': <Response [200]>,
 'T20I # 1871': <Response [200]>,
 'T20I # 1872': <Response [200]>,
 'T20I # 1873': <Response [200]>,
 'T20I # 1877': <Response [200]>,
 'T20I # 1878': <Response [200]>,
 'T20I # 1879': <Response [200]>}

In [12]:
df_batting = pd.DataFrame()
df_bowling = pd.DataFrame()

for id, response in dict1.items():
    soup2 = BeautifulSoup(response.content, 'html.parser')
    teams = soup2.find_all('span', {'class':'ds-text-tight-l ds-font-bold ds-text-ui-typo hover:ds-text-ui-typo-primary ds-block ds-truncate'})
    team_a = teams[0].string
    team_b = teams[1].string
    match = team_a + " VS " + team_b
    team_list = [team_a,team_b]
    
    batting_table = soup2.find_all('table', {"class":"ds-w-full ds-table ds-table-md ds-table-auto ci-scorecard-table"})
    bowling_table = soup2.find_all('table', {"class":"ds-w-full ds-table ds-table-md ds-table-auto"})
    
    for index, table in enumerate(batting_table):
        df_bat = pd.read_html(str(table))[0]
        df_bat.insert(loc=0, column='match', value = match )
        df_bat.insert(loc=1, column='team_innings', value = team_list[index] )
        df_bat.insert(loc=2, column='batting_pos', value = range(df_bat.shape[0]) )
        df_bat.insert(loc=len(df_bat.columns), column='match_id', value = id )
        df_batting = pd.concat([df_batting,df_bat],ignore_index=True)
    
    for index,table in enumerate(balling_table):
        df_bwl = pd.read_html(str(table))[0]
        df_bwl.insert(loc=0, column='match', value = match )
        df_bwl.insert(loc=1, column='bowling_team', value = team_list[index] )
        df_bwl.insert(loc=len(df_bwl.columns), column='match_id', value = id )
        df_bowling = pd.concat([df_bowling,df_bwl],ignore_index=True)

display(df_batting)
display(df_bowling)

,match,team_innings,batting_pos,BATTING,Unnamed: 1,R,B,M,4s,6s,SR,Unnamed: 8,Unnamed: 9,match_id
0,Namibia VS Sri Lanka,Namibia,0,Michael van Lingen,c Pramod Madushan b Chameera,3,6,7,0,0,50.00,NaN,NaN,T20I # 1823
1,Namibia VS Sri Lanka,Namibia,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T20I # 1823
2,Namibia VS Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,15,1,0,100.00,NaN,NaN,T20I # 1823
3,Namibia VS Sri Lanka,Namibia,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T20I # 1823
4,Namibia VS Sri Lanka,Namibia,4,Jan Nicol Loftie-Eaton,c †Mendis b Karunaratne,20,12,18,1,2,166.66,NaN,NaN,T20I # 1823
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1563,Pakistan VS England,England,11,Liam Livingstone,not out,1,1,3,0,0,100.00,NaN,NaN,T20I # 1879
1564,Pakistan VS England,England,12,Extras,"(lb 1, w 8)",9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T20I # 1879
1565,Pakistan VS England,England,13,TOTAL,19 Ov (RR: 7.26),138/5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T20I # 1879
1566,Pakistan VS England,England,14,"Did not bat: Sam Curran, Chris Woakes, Chris J...","Did not bat: Sam Curran, Chris Woakes, Chris J...","Did not bat: Sam Curran, Chris Woakes, Chris J...","Did not bat: Sam Curran, Chris Woakes, Chris J...","Did not bat: Sam Curran, Chris Woakes, Chris J...","Did not bat: Sam Curran, Chris Woakes, Chris J...","Did not bat: Sam Curran, Chris Woakes, Chris J...","Did not bat: Sam Curran, Chris Woakes, Chris J...","Did not bat: Sam Curran, Chris Woakes, Chris J...",NaN,T20I # 1879
1567,Pakistan VS England,England,15,"Fall of wickets: 1-7 (Alex Hales, 0.6 ov), 2-3...","Fall of wickets: 1-7 (Alex Hales, 0.6 ov), 2-3...","Fall of wickets: 1-7 (Alex Hales, 0.6 ov), 2-3...","Fall of wickets: 1-7 (Alex Hales, 0.6 ov), 2-3...","Fall of wickets: 1-7 (Alex Hales, 0.6 ov), 2-3...","Fall of wickets: 1-7 (Alex Hales, 0.6 ov), 2-3...","Fall of wickets: 1-7 (Alex Hales, 0.6 ov), 2-3...","Fall of wickets: 1-7 (Alex Hales, 0.6 ov), 2-3...","Fall of wickets: 1-7 (Alex Hales, 0.6 ov), 2-3...",NaN,T20I # 1879

,match,bowling_team,BOWLING,O,M,R,W,ECON,0s,4s,6s,WD,NB,match_id
0,Namibia VS Sri Lanka,Namibia,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0,T20I # 1823
1,Namibia VS Sri Lanka,Namibia,"14.2 to D Wiese, Big appeal for caught behind,...","14.2 to D Wiese, Big appeal for caught behind,...","14.2 to D Wiese, Big appeal for caught behind,...","14.2 to D Wiese, Big appeal for caught behind,...","14.2 to D Wiese, Big appeal for caught behind,...","14.2 to D Wiese, Big appeal for caught behind,...","14.2 to D Wiese, Big appeal for caught behind,...","14.2 to D Wiese, Big appeal for caught behind,...","14.2 to D Wiese, Big appeal for caught behind,...","14.2 to D Wiese, Big appeal for caught behind,...","14.2 to D Wiese, Big appeal for caught behind,...",T20I # 1823
2,Namibia VS Sri Lanka,Namibia,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0,T20I # 1823
3,Namibia VS Sri Lanka,Namibia,"1.2 to M van Lingen, Massive top-edge and Cham...","1.2 to M van Lingen, Massive top-edge and Cham...","1.2 to M van Lingen, Massive top-edge and Cham...","1.2 to M van Lingen, Massive top-edge and Cham...","1.2 to M van Lingen, Massive top-edge and Cham...","1.2 to M van Lingen, Massive top-edge and Cham...","1.2 to M van Lingen, Massive top-edge and Cham...","1.2 to M van Lingen, Massive top-edge and Cham...","1.2 to M van Lingen, Massive top-edge and Cham...","1.2 to M van Lingen, Massive top-edge and Cham...","1.2 to M van Lingen, Massive top-edge and Cham...",T20I # 1823
4,Namibia VS Sri Lanka,Namibia,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0,T20I # 1823
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
808,Pakistan VS England,England,Shadab Khan,4,0,20,1,5.00,10,1,0,0,0,T20I # 1879
809,Pakistan VS England,England,"12.3 to HC Brook, crashed hard, flat, straight...","12.3 to HC Brook, crashed hard, flat, straight...","12.3 to HC Brook, crashed hard, flat, straight...","12.3 to HC Brook, crashed hard, flat, straight...","12.3 to HC Brook, crashed hard, flat, straight...","12.3 to HC Brook, crashed hard, flat, straight...","12.3 to HC Brook, crashed hard, flat, straight...","12.3 to HC Brook, crashed hard, flat, straight...","12.3 to HC Brook, crashed hard, flat, straight...","12.3 to HC Brook, crashed hard, flat, straight...","12.3 to HC Brook, crashed hard, flat, straight...",T20I # 1879
810,Pakistan VS England,England,Mohammad Wasim,4,0,38,1,9.50,5,5,0,2,0,T20I # 1879
811,Pakistan VS England,England,"18.2 to MM Ali, full and straight, and Moeen i...","18.2 to MM Ali, full and straight, and Moeen i...","18.2 to MM Ali, full and straight, and Moeen i...","18.2 to MM Ali, full and straight, and Moeen i...","18.2 to MM Ali, full and straight, and Moeen i...","18.2 to MM Ali, full and straight, and Moeen i...","18.2 to MM Ali, full and straight, and Moeen i...","18.2 to MM Ali, full and straight, and Moeen i...","18.2 to MM Ali, full and straight, and Moeen i...","18.2 to MM Ali, full and straight, and Moeen i...","18.2 to MM Ali, full and straight, and Moeen i...",T20I # 1879
812,Pakistan VS England,England,Iftikhar Ahmed,0.5,0,13,0,15.60,0,1,1,0,0,T20I # 1879

In [13]:
df_batting.to_csv('batting_summary.csv')
df_balling.to_csv('bowlng_summary.csv')

### COLLECTING PLAYER DETAILS DATA

In [29]:
player_link_list = []
for id, response in dict1.items():
    soup3 = BeautifulSoup(response.content, 'html.parser')
    a = soup3.find_all('a', {'href':re.compile("^/player/")})
    for i in a:
       player_link_list.append(i.get('href'))

In [35]:
unique_players = list(set(player_link_list))

In [162]:
from selenium import webdriver
player_df = pd.DataFrame()
base_url = 'https://stats.espncricinfo.com'
for player in unique_players:
    browser = webdriver.Chrome()
    browser.get(base_url+player)
    res = browser.page_source
    player_soup = BeautifulSoup(res, 'html.parser')
    try:
        for i in player_soup.find_all('div',{'class':"ds-ml-auto ds-w-48 ds-h-48"}):
            img_link = i.find('img').get('src')
    except:
        img_link = ""
    player_div = player_soup.find('div', attrs={'class':'ds-p-4'})
    name = player_soup.find('h1', {'class':'ds-text-title-l ds-font-bold'}).text
    headers = player_div.find_all('p',attrs={'class':'ds-text-tight-m ds-font-regular ds-uppercase ds-text-ui-typo-mid'})
    headers = [i.text for i in headers]
    headers.insert(0,'Name')
    headers.append('Team')
    headers.append('image_link')
    values = player_div.find_all('span',attrs={'class':'ds-text-title-s ds-font-bold ds-text-ui-typo'})
    values = [i.text for i in values]
    try:
        player_team = player_div.find('div', {"class":"ds-grid lg:ds-grid-cols-3 ds-grid-cols-2 ds-gap-y-4"}).find('a').text
    except:
        player_team = ""
    name = player_soup.find('h1',{'class':'ds-text-title-l ds-font-bold'}).text
    values.insert(0,name)
    values.append(player_team)
    values.append(img_link)
    player_details_dict = dict(zip(headers,values))
    player_dff = pd.DataFrame(player_details_dict, index=[0])
    player_df = pd.concat([player_df,player_dff],ignore_index=True)
    browser.quit()

In [165]:
player_df.to_csv('player_details.csv')